// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcbQCidUWcIdB14ozDISTGDZJ8_fL62Ug',
    appId: '1:443101282126:web:8bac455164c42483de281f',
    messagingSenderId: '443101282126',
    projectId: 'oficinamecanica-8e118',
    authDomain: 'oficinamecanica-8e118.firebaseapp.com',
    databaseURL: 'https://oficinamecanica-8e118-default-rtdb.firebaseio.com',
    storageBucket: 'oficinamecanica-8e118.firebasestorage.app',
    measurementId: 'G-J3D1YGWE9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FKVxo9ge4P6IM9-W8H0QR7gVNfQJ6m8',
    appId: '1:443101282126:android:d571d863f3065ae4de281f',
    messagingSenderId: '443101282126',
    projectId: 'oficinamecanica-8e118',
    databaseURL: 'https://oficinamecanica-8e118-default-rtdb.firebaseio.com',
    storageBucket: 'oficinamecanica-8e118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGibDzpp6Sdl20-X1FqkWmx_nGTUkL9E',
    appId: '1:443101282126:ios:2dba7b1803563b85de281f',
    messagingSenderId: '443101282126',
    projectId: 'oficinamecanica-8e118',
    databaseURL: 'https://oficinamecanica-8e118-default-rtdb.firebaseio.com',
    storageBucket: 'oficinamecanica-8e118.firebasestorage.app',
    iosBundleId: 'com.example.flutterOficina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcbQCidUWcIdB14ozDISTGDZJ8_fL62Ug',
    appId: '1:443101282126:web:5ca18af6beb68792de281f',
    messagingSenderId: '443101282126',
    projectId: 'oficinamecanica-8e118',
    authDomain: 'oficinamecanica-8e118.firebaseapp.com',
    databaseURL: 'https://oficinamecanica-8e118-default-rtdb.firebaseio.com',
    storageBucket: 'oficinamecanica-8e118.firebasestorage.app',
    measurementId: 'G-NKQM5HXY12',
  );
}
